services:
    astro:
        build: ./local
        image: php:public
        container_name: astro
        volumes:
            - ./:/var/www/html
        ports:
            - "8000:8000"
        depends_on:
            - db
    db:
        image: mysql:8.0
        container_name: astro_db
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: free_astro
            MYSQL_USER: fen_user
            MYSQL_PASSWORD: fen_password
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
